### PR TITLE
Support rdp:// protocol

### PR DESCRIPTION
**Pull request by pmiossec**

### CODE REVIEW

**Comment by damousys** [comment]
Can you tell me how I can use /Admin with this beautiful tool ?
&admin of &=admin doesn't work

**Comment by mpking828** [comment]
> _No description provided._

Sorry, new to Git.  Is there a binary for your improvements, since the original project owner seems to have disappeared.

**Comment by pmiossec** [comment]
@mpking828 I have made a release where you can download the exe ( https://github.com/pmiossec/MstscLauncher/releases/tag/v1.1.0 )

PS: Even if that's better to build it yourself to prevent downloading exe you don't trust....

**Comment by richard-green** [comment]
Hi @damousys, @mpking828, @pmiossec I apologise for this pull request completely slipping me by! Thanks for the work!

**Comment by richard-green** [comment]
@damousys I have updated the readme to explain how to use the parameters correctly https://github.com/richard-green/MstscLauncher/blob/master/README.md

**Pull request merged**
